###GET request for products
GET https://63f45eca3f99f5855dae29dc.mockapi.io/users


### add new product
POST https://63f45eca3f99f5855dae29dc.mockapi.io/products
Content-Type: application/json

{
    
  }


### DELETE product
DELETE https://63f45eca3f99f5855dae29dc.mockapi.io/products/92

###GET request for users
GET https://63f45eca3f99f5855dae29dc.mockapi.io/users

### add new user
POST https://63f45eca3f99f5855dae29dc.mockapi.io/products
Content-Type: application/json

{
      "special": "BUY MORE SAVE MORE",
      "name": "Harbor Bay Moisture-Wicking Jersey T-Shirt",
      "category": "tshirt",
      "price": 1498,
      "minPrice": 1498,
      "maxPrice": 2676,
      "sale-message": "Save Up To 44%",
      "images": [
        "https://images.dxl.com/is/image/CasualMale/p92989yolk_yellow?$splp$",
        "https://images.dxl.com/is/image/CasualMale/p92989burnt_orange?$splp$",
        "https://images.dxl.com/is/image/CasualMale/p92989coral_quartz?$splp$",
        "https://images.dxl.com/is/image/CasualMale/p92989sodalite_blue?$splp$"
      ],
      "color": [
        "https://images.dxl.com/is/image/CasualMale/p92989yolk_yellow_sw?$Swatch$",
        "https://images.dxl.com/is/image/CasualMale/p92989burnt_orange_sw?$Swatch$",
        "https://images.dxl.com/is/image/CasualMale/p92989coral_quartz_sw?$Swatch$",
        "https://images.dxl.com/is/image/CasualMale/p92989sodalite_blue_sw?$Swatch$"
      ]
}


###GET request for products
GET https://63f45eca3f99f5855dae29dc.mockapi.io/products/8


###Update
PUT https://63f45eca3f99f5855dae29dc.mockapi.io/products/8
Content-Type: application/json

{
 "id": "8",
  "special": "NEW ITEM",
  "name": "Polo Ralph Lauren Logo Jersey Classic T-Shirt",
  "category": "tshirt",
  "price": 5797,
  "minPrice": 5797,
  "images": [
    "https://images.dxl.com/is/image/CasualMale/pB9899?$splp$"
  ],
  "color": [
    "https://images.dxl.com/is/image/CasualMale/pB9899white_sw?$Swatch$"
  ],
  "maxPrice": 2676,
  "sale-message": "Save Up To 58%"
}

### update order status 
PATCH https://63f45eca3f99f5855dae29dc.mockapi.io/users/1
Content-Type: application/json

{
  "orderStatus": "Return/Exchange Requested",
  "estimatedDate": "28/02/2023"
}
