GET https://63c4d1cdf80fabd877db7506.mockapi.io/newproduct
###
GET https://63c4d1cdf80fabd877db7506.mockapi.io/newproduct

###
DELETE https://63c4d1cdf80fabd877db7506.mockapi.io/newproduct/103


###
POST https://63c4d1cdf80fabd877db7506.mockapi.io/newproduct
Content-Type: application/json

{


     
  
 

  "name": "Burnout Wash Boyfriend Tee",
  "img": "https://www.aeropostale.com/dw/image/v2/BBSG_PRD/on/demandware.static/-/Sites-master-catalog-aeropostale/default/dwabfb2239/81433993_649_main.jpg?sw=478&sh=557&sm=fit&sfrm=jpg",
  "price": 800,
  "category": "Women",
  "colour": "Pink",
  "type": "Dresses",
  "Size": "L"
  }

###
 GET https://63f45eca3f99f5855dae29dc.mockapi.io/products




  
    